spring.application.name=learning

server.port=8080

spring.datasource.url=jdbc:mysql://localhost:3306/company
spring.datasource.username=root
spring.datasource.password=root123A@1

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
